const INITIAL_BALANCE = 50;
const RESERVED_NFTS = 100;
const NFT_FEE = 5;
const NFTS_PER_GYM = 3;
const BATTLE_DURATION = 300; // 5 mins
const HEAL_FEE = 1;

module.exports = {
  INITIAL_BALANCE,
  RESERVED_NFTS,
  NFT_FEE,
  NFTS_PER_GYM,
  BATTLE_DURATION,
  HEAL_FEE,
};
